#!/usr/bin/env python

# from janki import *
from janki.janki.ui.setup import setup
from janki.janki.ui.main  import main
from janki.janki.common.vars import DIR
from argparse import ArgumentParser
import os
from os.path import join as opj, dirname as opd, abspath


descr="""*** Janki main script ***"""

parser = ArgumentParser(description=descr)
parser.add_argument('action', nargs='?', choices=[None, 'setup'], default=None, help='Main janki action.')
args = parser.parse_args()

if args.action == None:
    main()
elif args.action == 'setup':
    setup(opj(DIR, 'config'))
