#!/usr/bin/env python

from janki.janki.common.exceptions import *
from janki.janki.ui.setup          import setup
from janki.janki.ui.userinput      import dinput
from janki.janki.common.vars       import DIR, clear

from argparse import ArgumentParser
import os, sys
from os.path import join as opj, dirname as opd, abspath

parser = ArgumentParser(description='Janki main script')
parser.add_argument('action', nargs='?', choices=[None, 'setup'], default=None, help='Main janki action.')
args = parser.parse_args()

def mainscreen():
    clear()
    print(f"{16*'*'}\nWelcome to Janki \n{16*'*'}\n")
    from janki.janki.core.config import readconfig
    try:
        global config
        config = readconfig(verbose=False)
        print(f"Install path:    {DIR}")
        print(f"Config path:     {config['__file__']}")
        print(f"Collection path: {config['COLPATH']}")
        print(f"Selected deck:   {config['DECK']}\n")
        print('Actions: (s)earch, (q)uit')
    except ConfigError:
        print("Could not read the config. Please run 'janki setup' for more help.")
        sys.exit(1)


if args.action == None:
    mainscreen()
    action = dinput('What to do?', choices=['s','q'], default='s')
    if action == 's':
        from janki.janki.ui.search import search
        search()
    elif not action:
        clear()
        sys.exit()
elif args.action == 'setup':
    setup(opj(DIR, 'config'))
